### ISSUE TITLE
Ansible status 

### ISSUE THREAD

**Issue by Funk-Burasuta** [Dewb/monome-rack#88] opened 2022-05-20 02:55 UTC
In beginning of this year there was available a version of Ansible that ran kria.
Whatever happened to it?

**Comment by Dewb** [comment] 2022-05-20 03:55
It’s not ready for general use because doesn’t support saving its state to the VCV Rack patch yet. Ansible’s runtime memory state is much more complicated than the other modules, so it needs some additional plumbing.

It was briefly enabled during the Rack 2.0 beta so it could be tested, but after that it was disabled so people wouldn’t try to use it and lose work. If you want to use it despite that limitation you can re-enable it in plugin.json.

**Comment by Dewb** [comment] 2022-05-21 01:49
Duplicate of #18.

**Closed by Dewb** 2022-05-21 01:49 UTC

**Comment by Dewb** [comment] 2023-01-09 03:57
Ansible is now available in 2.0.1-beta release: https://github.com/Dewb/monome-rack/releases/tag/v2.0.1-beta
